package: "sesterl_json"

source_directories:
  - "./src"

test_directories:
  - "./test"

main_module: "Json"

dependencies:
  - name: "sesterl_stdlib"
    source:
      type: "git"
      repository: "https://github.com/gfngfn/sesterl_stdlib"
      spec:
        type: "branch"
        value: "master"

test_dependencies:
  - name: "sesterl_testing"
    source:
      type: "git"
      repository: "https://github.com/gfngfn/sesterl_testing"
      spec:
        type: "branch"
        value: "master"

erlang:
  output_directory: "./_generated"
  test_output_directory: "./_generated_test"
  erlang_dependencies:
    - name: "jsone"
      source:
        type: "hex"
        version: "1.5.7"
